name: Compile and Run
on: push

jobs:
  compile_and_run:
    runs-on: ubuntu-latest
    name: Compile and Run
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Run
        run: sh compile_and_run.sh
